name: gokdis
description: A new Flutter project.

publish_to: 'none' 



environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.31.15
  shared_preferences: ^2.2.2
  http: ^1.2.1
  flutter_barcode_scanner: ^2.0.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  epitaph_ips:
    git:
      url: https://github.com/gokdis/epitaph_ips
      ref: main
  ml_linalg: ^13.12.2
  moving_average: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1



flutter:


  uses-material-design: true
  assets:
    - assets/images/supermarket.png
    - assets/images/supermarketold.png
    - assets/cells.json
    - .env